version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: ToDoAPI/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT:-Docker}

  training-database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      MSSQL_SA_PASSWORD: "Passw1234"
      ACCEPT_EULA: "Y"
    volumes:
      - data:/var/opt/mssql
    restart: unless-stopped    
    ports:
      - "1433:1433"
volumes:
  data: