// <auto-generated />
using System;
using CandidateAPIApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandidateAPIApplication.Migrations
{
    [DbContext(typeof(CandidatesContext))]
    [Migration("20230509032635_Delete_table_CommentAndCandidate")]
    partial class Delete_table_CommentAndCandidate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidateAPIApplication.Models.CandidatesModel", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathResume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCodeID")
                        .HasColumnType("int");

                    b.Property<int?>("StatusModelStatusCodeID")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("StatusModelStatusCodeID");

                    b.ToTable("CandidatesProfiles");
                });

            modelBuilder.Entity("CandidateAPIApplication.Models.CommentsScoresModel", b =>
                {
                    b.Property<int>("CommentScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentScoreId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scores")
                        .HasColumnType("int");

                    b.HasKey("CommentScoreId");

                    b.HasIndex("CommentScoreId")
                        .IsUnique();

                    b.ToTable("CommentsAndScoresProfiles");
                });

            modelBuilder.Entity("CandidateAPIApplication.Models.DateAppointmentsModel", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("EndAppointment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartAppointment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentID");

                    b.HasIndex("AppointmentID")
                        .IsUnique();

                    b.ToTable("DateAppointmentProfiles");
                });

            modelBuilder.Entity("CandidateAPIApplication.Models.StatusModel", b =>
                {
                    b.Property<int>("StatusCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusCodeID"));

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusCodeID");

                    b.HasIndex("StatusCodeID")
                        .IsUnique();

                    b.ToTable("StatusCandidatesProfiles");
                });

            modelBuilder.Entity("CandidateAPIApplication.Models.CandidatesModel", b =>
                {
                    b.HasOne("CandidateAPIApplication.Models.StatusModel", null)
                        .WithMany("ListCandidates")
                        .HasForeignKey("StatusModelStatusCodeID");
                });

            modelBuilder.Entity("CandidateAPIApplication.Models.StatusModel", b =>
                {
                    b.Navigation("ListCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
